# Generated by Django 3.0 on 2021-03-27 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0004_tag_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelectedRecipies',
            new_name='SelectedRecipe',
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('orange', 'оранжевый'), ('green', 'зеленый'), ('purple', 'фиолетовый')], max_length=20, unique=True, verbose_name='цвет'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(choices=[('завтрак', 'завтрак'), ('обед', 'обед'), ('ужин', 'ужин')], max_length=20, unique=True, verbose_name='название'),
        ),
    ]
