# Generated by Django 3.0 on 2021-03-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20210327_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredientamount',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='количество'),
        ),
    ]
